"""initial_reset

Revision ID: 77a7ff58bbeb
Revises: 285289c7f497
Create Date: 2025-11-27 19:03:13.528817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77a7ff58bbeb'
down_revision: Union[str, Sequence[str], None] = '285289c7f497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_online', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_online')
    op.drop_column('user', 'is_online')
    # ### end Alembic commands ###
