"""empty message

Revision ID: 00048ac9d805
Revises: da613880105e
Create Date: 2025-11-12 16:31:06.254255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00048ac9d805'
down_revision = 'da613880105e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_peso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_peso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ejercicio', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('peso', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_peso_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_peso_pkey'))
    )
    # ### end Alembic commands ###
