"""empty message

Revision ID: 0ec6842fd8f5
Revises: 99be3329c653
Create Date: 2025-07-06 14:59:17.722017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec6842fd8f5'
down_revision = '99be3329c653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.alter_column('semana',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.alter_column('semana',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
