"""empty message

Revision ID: 106a5de960a2
Revises: f34d0ebafb8d
Create Date: 2025-10-13 15:56:43.261375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '106a5de960a2'
down_revision = 'f34d0ebafb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('wod')
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notas')
        batch_op.drop_column('user_id')

    op.create_table('wod',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wodFecha', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('wodDescripcion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('wodComoRealizo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wodSentimiento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('wod_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wod_pkey'))
    )
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ejercicio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('peso', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('log_pkey'))
    )
    # ### end Alembic commands ###
