"""empty message

Revision ID: 25e8a440bc84
Revises: 1afa7fcc38a2
Create Date: 2025-11-11 22:40:21.254741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e8a440bc84'
down_revision = '1afa7fcc38a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pesos')
    # ### end Alembic commands ###
