"""empty message

Revision ID: 37028edb05e1
Revises: 0ec6842fd8f5
Create Date: 2025-07-06 15:14:10.914997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37028edb05e1'
down_revision = '0ec6842fd8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.alter_column('semana',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('dia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bloque_a',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bloque_b',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bloque_c',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bloque_d',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uix_semana_dia'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uix_semana_dia'), ['semana', 'dia'])
        batch_op.alter_column('bloque_d',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bloque_c',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bloque_b',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bloque_a',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('semana',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
