"""empty message

Revision ID: 3debe49e59c2
Revises: 106a5de960a2
Create Date: 2025-10-13 16:03:55.580839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3debe49e59c2'
down_revision = '106a5de960a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('ejercicio', sa.String(length=120), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wod_fecha', sa.String(length=10), nullable=False),
    sa.Column('wod_descripcion', sa.Text(), nullable=False),
    sa.Column('wod_como_realizo', sa.Text(), nullable=True),
    sa.Column('wod_sentimiento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('planificacion_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('notas')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('planificacion_user_id_fkey'), 'user', ['user_id'], ['id'])

    op.drop_table('user_wod')
    op.drop_table('user_log')
    # ### end Alembic commands ###
