"""empty message

Revision ID: 5a041e65dd89
Revises: 37028edb05e1
Create Date: 2025-07-12 17:15:14.895858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a041e65dd89'
down_revision = '37028edb05e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.alter_column('semana',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('dia',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificaciones', schema=None) as batch_op:
        batch_op.alter_column('dia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('semana',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
