"""empty message

Revision ID: 82fef16eb999
Revises: 3debe49e59c2
Create Date: 2025-10-13 16:08:05.410600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fef16eb999'
down_revision = '3debe49e59c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_wod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('como_realizo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sentimiento', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_wod_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('wod_como_realizo')
        batch_op.drop_column('wod_descripcion')
        batch_op.drop_column('wod_fecha')
        batch_op.drop_column('wod_sentimiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_wod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wod_sentimiento', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wod_fecha', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wod_descripcion', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wod_como_realizo', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_wod_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('sentimiento')
        batch_op.drop_column('como_realizo')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_log_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
