"""empty message

Revision ID: 9524279b617f
Revises: e01fd9393100
Create Date: 2025-10-04 17:39:22.570552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9524279b617f'
down_revision = 'e01fd9393100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.String(length=10), nullable=False))
        batch_op.drop_column('semana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semana', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
