"""empty message

Revision ID: 98cbafbc20cf
Revises: 5a041e65dd89
Create Date: 2025-07-12 17:29:40.253822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98cbafbc20cf'
down_revision = '5a041e65dd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.String(length=10), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('bloque_a', sa.String(length=255), nullable=True),
    sa.Column('bloque_b', sa.String(length=255), nullable=True),
    sa.Column('bloque_c', sa.String(length=255), nullable=True),
    sa.Column('bloque_d', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planificaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planificaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semana', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('dia', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bloque_a', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bloque_b', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bloque_c', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bloque_d', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('planificaciones_pkey'))
    )
    op.drop_table('planificacion')
    # ### end Alembic commands ###
