"""empty message

Revision ID: 99be3329c653
Revises: 83eac453ab96
Create Date: 2025-07-06 14:50:52.980630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99be3329c653'
down_revision = '83eac453ab96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.String(length=7), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('bloque_a', sa.Text(), nullable=True),
    sa.Column('bloque_b', sa.Text(), nullable=True),
    sa.Column('bloque_c', sa.Text(), nullable=True),
    sa.Column('bloque_d', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semana', 'dia', name='uix_semana_dia')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('planificaciones')
    # ### end Alembic commands ###
