"""empty message

Revision ID: cc684b8c4e11
Revises: d66b5935713f
Create Date: 2025-11-12 17:58:03.937547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc684b8c4e11'
down_revision = 'd66b5935713f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_peso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_peso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ejercicio', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('peso', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_peso_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_peso_pkey'))
    )
    # ### end Alembic commands ###
