"""Permitir null en valor de UserPeso

Revision ID: ce079c3a7ac6
Revises: 814c6b50d69c
Create Date: 2025-11-19 17:54:03.229972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce079c3a7ac6'
down_revision = '814c6b50d69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('max_clean_jerk')
        batch_op.drop_column('max_snatch')
        batch_op.drop_column('max_front_squat')
        batch_op.drop_column('max_push_jerk')
        batch_op.drop_column('max_bench_press')
        batch_op.drop_column('max_clean')
        batch_op.drop_column('max_back_squat')
        batch_op.drop_column('max_deadlift')

    with op.batch_alter_table('user_peso', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_peso', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_deadlift', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_back_squat', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_clean', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_bench_press', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_push_jerk', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_front_squat', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_snatch', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('max_clean_jerk', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
