"""empty message

Revision ID: da613880105e
Revises: 25e8a440bc84
Create Date: 2025-11-12 15:30:47.676762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da613880105e'
down_revision = '25e8a440bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_peso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ejercicio', sa.String(length=120), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_pesos')
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.drop_column('bloque_e')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloque_e', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('user_pesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ejercicio', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('peso', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_pesos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pesos_pkey'))
    )
    op.drop_table('user_peso')
    # ### end Alembic commands ###
