"""Agregar bloque_e a Planificacion

Revision ID: db7ef9ef5be2
Revises: 00048ac9d805
Create Date: 2025-11-12 16:34:42.180839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7ef9ef5be2'
down_revision = '00048ac9d805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloque_e', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.drop_column('bloque_e')

    # ### end Alembic commands ###
