"""Fix user peso unique constraint

Revision ID: e719a36c12cc
Revises: ce079c3a7ac6
Create Date: 2025-11-19 23:21:47.865979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e719a36c12cc'
down_revision = 'ce079c3a7ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_peso', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_ejercicio', ['user_id', 'ejercicio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_peso', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_ejercicio', type_='unique')

    # ### end Alembic commands ###
