"""empty message

Revision ID: f34d0ebafb8d
Revises: 9524279b617f
Create Date: 2025-10-06 17:39:03.614848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34d0ebafb8d'
down_revision = '9524279b617f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('ejercicio', sa.String(length=100), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wodFecha', sa.String(length=10), nullable=False),
    sa.Column('wodDescripcion', sa.Text(), nullable=False),
    sa.Column('wodComoRealizo', sa.Text(), nullable=True),
    sa.Column('wodSentimiento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wod')
    op.drop_table('log')
    # ### end Alembic commands ###
